apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: system-controllers
namespace: kube-system

resources:
- agones
- cert-manager
- democratic-csi
- reflector
- sealed-secrets
- secret-generator
- traefik
